version: '3.3'

services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  hubot:
    build:
      context: .
      dockerfile: ./etc/docker/hubot.Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "9001:9001"
    volumes:
      - type: volume
        source: .
        target: /hubot

  nginx:
    image: nginx
    depends_on:
      - hubot
    ports:
      - "8080:80"
      - "9443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/www/index.html:/var/www/index.html
