version: '3.2'
services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    networks:
      - server
    volumes:
      - /data:/data

  hubot:
    image: "mwop/zfbot:0.8.4"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - server

  nginx:
    image: "mwop/zfbot-nginx:0.4.0"
    depends_on:
      - hubot
    networks:
      - server

  caddy:
    image: "mwop/zfbot-caddy:0.1.0"
    env_file:
      - .caddy.env
    depends_on:
      - nginx
    restart: on-failure
    volumes:
      - /data/caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server
      - public

networks:
  public:
    external: true
  server:
