version: '3.2'
services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    networks:
      - server
    volumes:
      - /data:/data

  hubot:
    image: "mwop/zfbot:0.4.2"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - server

  nginx:
    image: "mwop/zfbot-nginx:0.2.2"
    depends_on:
      - hubot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
      - server

networks:
  public:
    external: true
  server:
